// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Struct.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
#include "Enum.pb.h"
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_Struct_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_Struct_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_Struct_2eproto;
namespace Protocol {
class ActorInfo;
struct ActorInfoDefaultTypeInternal;
extern ActorInfoDefaultTypeInternal _ActorInfo_default_instance_;
class BuffData;
struct BuffDataDefaultTypeInternal;
extern BuffDataDefaultTypeInternal _BuffData_default_instance_;
class ObjectInfo;
struct ObjectInfoDefaultTypeInternal;
extern ObjectInfoDefaultTypeInternal _ObjectInfo_default_instance_;
class TiredOfficeWorkerStat;
struct TiredOfficeWorkerStatDefaultTypeInternal;
extern TiredOfficeWorkerStatDefaultTypeInternal _TiredOfficeWorkerStat_default_instance_;
}  // namespace Protocol
PROTOBUF_NAMESPACE_OPEN
template<> ::Protocol::ActorInfo* Arena::CreateMaybeMessage<::Protocol::ActorInfo>(Arena*);
template<> ::Protocol::BuffData* Arena::CreateMaybeMessage<::Protocol::BuffData>(Arena*);
template<> ::Protocol::ObjectInfo* Arena::CreateMaybeMessage<::Protocol::ObjectInfo>(Arena*);
template<> ::Protocol::TiredOfficeWorkerStat* Arena::CreateMaybeMessage<::Protocol::TiredOfficeWorkerStat>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Protocol {

// ===================================================================

class BuffData final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.BuffData) */ {
 public:
  inline BuffData() : BuffData(nullptr) {}
  ~BuffData() override;
  explicit PROTOBUF_CONSTEXPR BuffData(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  BuffData(const BuffData& from);
  BuffData(BuffData&& from) noexcept
    : BuffData() {
    *this = ::std::move(from);
  }

  inline BuffData& operator=(const BuffData& from) {
    CopyFrom(from);
    return *this;
  }
  inline BuffData& operator=(BuffData&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BuffData& default_instance() {
    return *internal_default_instance();
  }
  static inline const BuffData* internal_default_instance() {
    return reinterpret_cast<const BuffData*>(
               &_BuffData_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(BuffData& a, BuffData& b) {
    a.Swap(&b);
  }
  inline void Swap(BuffData* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BuffData* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BuffData* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<BuffData>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const BuffData& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const BuffData& from) {
    BuffData::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(BuffData* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.BuffData";
  }
  protected:
  explicit BuffData(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVictimsFieldNumber = 3,
    kBuffIdFieldNumber = 1,
    kRemainTimeFieldNumber = 2,
  };
  // repeated uint64 victims = 3;
  int victims_size() const;
  private:
  int _internal_victims_size() const;
  public:
  void clear_victims();
  private:
  uint64_t _internal_victims(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      _internal_victims() const;
  void _internal_add_victims(uint64_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      _internal_mutable_victims();
  public:
  uint64_t victims(int index) const;
  void set_victims(int index, uint64_t value);
  void add_victims(uint64_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
      victims() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
      mutable_victims();

  // uint64 buffId = 1;
  void clear_buffid();
  uint64_t buffid() const;
  void set_buffid(uint64_t value);
  private:
  uint64_t _internal_buffid() const;
  void _internal_set_buffid(uint64_t value);
  public:

  // float remainTime = 2;
  void clear_remaintime();
  float remaintime() const;
  void set_remaintime(float value);
  private:
  float _internal_remaintime() const;
  void _internal_set_remaintime(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.BuffData)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t > victims_;
    mutable std::atomic<int> _victims_cached_byte_size_;
    uint64_t buffid_;
    float remaintime_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ActorInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ActorInfo) */ {
 public:
  inline ActorInfo() : ActorInfo(nullptr) {}
  ~ActorInfo() override;
  explicit PROTOBUF_CONSTEXPR ActorInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ActorInfo(const ActorInfo& from);
  ActorInfo(ActorInfo&& from) noexcept
    : ActorInfo() {
    *this = ::std::move(from);
  }

  inline ActorInfo& operator=(const ActorInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ActorInfo& operator=(ActorInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ActorInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ActorInfo* internal_default_instance() {
    return reinterpret_cast<const ActorInfo*>(
               &_ActorInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(ActorInfo& a, ActorInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ActorInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ActorInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ActorInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ActorInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ActorInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ActorInfo& from) {
    ActorInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ActorInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ActorInfo";
  }
  protected:
  explicit ActorInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kIdFieldNumber = 1,
    kPosXFieldNumber = 2,
    kPosYFieldNumber = 3,
  };
  // int64 id = 1;
  void clear_id();
  int64_t id() const;
  void set_id(int64_t value);
  private:
  int64_t _internal_id() const;
  void _internal_set_id(int64_t value);
  public:

  // float posX = 2;
  void clear_posx();
  float posx() const;
  void set_posx(float value);
  private:
  float _internal_posx() const;
  void _internal_set_posx(float value);
  public:

  // float posY = 3;
  void clear_posy();
  float posy() const;
  void set_posy(float value);
  private:
  float _internal_posy() const;
  void _internal_set_posy(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ActorInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int64_t id_;
    float posx_;
    float posy_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class ObjectInfo final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.ObjectInfo) */ {
 public:
  inline ObjectInfo() : ObjectInfo(nullptr) {}
  ~ObjectInfo() override;
  explicit PROTOBUF_CONSTEXPR ObjectInfo(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  ObjectInfo(const ObjectInfo& from);
  ObjectInfo(ObjectInfo&& from) noexcept
    : ObjectInfo() {
    *this = ::std::move(from);
  }

  inline ObjectInfo& operator=(const ObjectInfo& from) {
    CopyFrom(from);
    return *this;
  }
  inline ObjectInfo& operator=(ObjectInfo&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const ObjectInfo& default_instance() {
    return *internal_default_instance();
  }
  static inline const ObjectInfo* internal_default_instance() {
    return reinterpret_cast<const ObjectInfo*>(
               &_ObjectInfo_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(ObjectInfo& a, ObjectInfo& b) {
    a.Swap(&b);
  }
  inline void Swap(ObjectInfo* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(ObjectInfo* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  ObjectInfo* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<ObjectInfo>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const ObjectInfo& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const ObjectInfo& from) {
    ObjectInfo::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ObjectInfo* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.ObjectInfo";
  }
  protected:
  explicit ObjectInfo(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStateFieldNumber = 1,
    kDirFieldNumber = 2,
  };
  // .Protocol.OBJECT_STATE_TYPE state = 1;
  void clear_state();
  ::Protocol::OBJECT_STATE_TYPE state() const;
  void set_state(::Protocol::OBJECT_STATE_TYPE value);
  private:
  ::Protocol::OBJECT_STATE_TYPE _internal_state() const;
  void _internal_set_state(::Protocol::OBJECT_STATE_TYPE value);
  public:

  // .Protocol.DIR_TYPE dir = 2;
  void clear_dir();
  ::Protocol::DIR_TYPE dir() const;
  void set_dir(::Protocol::DIR_TYPE value);
  private:
  ::Protocol::DIR_TYPE _internal_dir() const;
  void _internal_set_dir(::Protocol::DIR_TYPE value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.ObjectInfo)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int state_;
    int dir_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// -------------------------------------------------------------------

class TiredOfficeWorkerStat final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Protocol.TiredOfficeWorkerStat) */ {
 public:
  inline TiredOfficeWorkerStat() : TiredOfficeWorkerStat(nullptr) {}
  ~TiredOfficeWorkerStat() override;
  explicit PROTOBUF_CONSTEXPR TiredOfficeWorkerStat(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  TiredOfficeWorkerStat(const TiredOfficeWorkerStat& from);
  TiredOfficeWorkerStat(TiredOfficeWorkerStat&& from) noexcept
    : TiredOfficeWorkerStat() {
    *this = ::std::move(from);
  }

  inline TiredOfficeWorkerStat& operator=(const TiredOfficeWorkerStat& from) {
    CopyFrom(from);
    return *this;
  }
  inline TiredOfficeWorkerStat& operator=(TiredOfficeWorkerStat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const TiredOfficeWorkerStat& default_instance() {
    return *internal_default_instance();
  }
  static inline const TiredOfficeWorkerStat* internal_default_instance() {
    return reinterpret_cast<const TiredOfficeWorkerStat*>(
               &_TiredOfficeWorkerStat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(TiredOfficeWorkerStat& a, TiredOfficeWorkerStat& b) {
    a.Swap(&b);
  }
  inline void Swap(TiredOfficeWorkerStat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(TiredOfficeWorkerStat* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  TiredOfficeWorkerStat* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<TiredOfficeWorkerStat>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const TiredOfficeWorkerStat& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const TiredOfficeWorkerStat& from) {
    TiredOfficeWorkerStat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(TiredOfficeWorkerStat* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Protocol.TiredOfficeWorkerStat";
  }
  protected:
  explicit TiredOfficeWorkerStat(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kHpFieldNumber = 1,
    kHealtemDropRateFieldNumber = 2,
    kSpeedFieldNumber = 3,
    kChaseSpeedFieldNumber = 4,
    kPlayerDetectionXFieldNumber = 5,
    kPlayerDetectionYFieldNumber = 6,
    kKnockBackDistanceFieldNumber = 7,
    kAttackRangeXFieldNumber = 8,
    kAttackRangeYFieldNumber = 9,
    kAttackFieldNumber = 10,
    kIdleTimeFieldNumber = 11,
    kMovingDistanceFieldNumber = 12,
    kMovementLimitXFieldNumber = 13,
    kMovementLimitYFieldNumber = 14,
  };
  // int32 hp = 1;
  void clear_hp();
  int32_t hp() const;
  void set_hp(int32_t value);
  private:
  int32_t _internal_hp() const;
  void _internal_set_hp(int32_t value);
  public:

  // float healtemDropRate = 2;
  void clear_healtemdroprate();
  float healtemdroprate() const;
  void set_healtemdroprate(float value);
  private:
  float _internal_healtemdroprate() const;
  void _internal_set_healtemdroprate(float value);
  public:

  // float speed = 3;
  void clear_speed();
  float speed() const;
  void set_speed(float value);
  private:
  float _internal_speed() const;
  void _internal_set_speed(float value);
  public:

  // float chaseSpeed = 4;
  void clear_chasespeed();
  float chasespeed() const;
  void set_chasespeed(float value);
  private:
  float _internal_chasespeed() const;
  void _internal_set_chasespeed(float value);
  public:

  // int32 playerDetectionX = 5;
  void clear_playerdetectionx();
  int32_t playerdetectionx() const;
  void set_playerdetectionx(int32_t value);
  private:
  int32_t _internal_playerdetectionx() const;
  void _internal_set_playerdetectionx(int32_t value);
  public:

  // int32 playerDetectionY = 6;
  void clear_playerdetectiony();
  int32_t playerdetectiony() const;
  void set_playerdetectiony(int32_t value);
  private:
  int32_t _internal_playerdetectiony() const;
  void _internal_set_playerdetectiony(int32_t value);
  public:

  // int32 knockBackDistance = 7;
  void clear_knockbackdistance();
  int32_t knockbackdistance() const;
  void set_knockbackdistance(int32_t value);
  private:
  int32_t _internal_knockbackdistance() const;
  void _internal_set_knockbackdistance(int32_t value);
  public:

  // int32 attackRangeX = 8;
  void clear_attackrangex();
  int32_t attackrangex() const;
  void set_attackrangex(int32_t value);
  private:
  int32_t _internal_attackrangex() const;
  void _internal_set_attackrangex(int32_t value);
  public:

  // int32 attackRangeY = 9;
  void clear_attackrangey();
  int32_t attackrangey() const;
  void set_attackrangey(int32_t value);
  private:
  int32_t _internal_attackrangey() const;
  void _internal_set_attackrangey(int32_t value);
  public:

  // int32 attack = 10;
  void clear_attack();
  int32_t attack() const;
  void set_attack(int32_t value);
  private:
  int32_t _internal_attack() const;
  void _internal_set_attack(int32_t value);
  public:

  // float idleTime = 11;
  void clear_idletime();
  float idletime() const;
  void set_idletime(float value);
  private:
  float _internal_idletime() const;
  void _internal_set_idletime(float value);
  public:

  // float movingDistance = 12;
  void clear_movingdistance();
  float movingdistance() const;
  void set_movingdistance(float value);
  private:
  float _internal_movingdistance() const;
  void _internal_set_movingdistance(float value);
  public:

  // float movementLimitX = 13;
  void clear_movementlimitx();
  float movementlimitx() const;
  void set_movementlimitx(float value);
  private:
  float _internal_movementlimitx() const;
  void _internal_set_movementlimitx(float value);
  public:

  // float movementLimitY = 14;
  void clear_movementlimity();
  float movementlimity() const;
  void set_movementlimity(float value);
  private:
  float _internal_movementlimity() const;
  void _internal_set_movementlimity(float value);
  public:

  // @@protoc_insertion_point(class_scope:Protocol.TiredOfficeWorkerStat)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    int32_t hp_;
    float healtemdroprate_;
    float speed_;
    float chasespeed_;
    int32_t playerdetectionx_;
    int32_t playerdetectiony_;
    int32_t knockbackdistance_;
    int32_t attackrangex_;
    int32_t attackrangey_;
    int32_t attack_;
    float idletime_;
    float movingdistance_;
    float movementlimitx_;
    float movementlimity_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_Struct_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// BuffData

// uint64 buffId = 1;
inline void BuffData::clear_buffid() {
  _impl_.buffid_ = uint64_t{0u};
}
inline uint64_t BuffData::_internal_buffid() const {
  return _impl_.buffid_;
}
inline uint64_t BuffData::buffid() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.buffId)
  return _internal_buffid();
}
inline void BuffData::_internal_set_buffid(uint64_t value) {
  
  _impl_.buffid_ = value;
}
inline void BuffData::set_buffid(uint64_t value) {
  _internal_set_buffid(value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.buffId)
}

// float remainTime = 2;
inline void BuffData::clear_remaintime() {
  _impl_.remaintime_ = 0;
}
inline float BuffData::_internal_remaintime() const {
  return _impl_.remaintime_;
}
inline float BuffData::remaintime() const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.remainTime)
  return _internal_remaintime();
}
inline void BuffData::_internal_set_remaintime(float value) {
  
  _impl_.remaintime_ = value;
}
inline void BuffData::set_remaintime(float value) {
  _internal_set_remaintime(value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.remainTime)
}

// repeated uint64 victims = 3;
inline int BuffData::_internal_victims_size() const {
  return _impl_.victims_.size();
}
inline int BuffData::victims_size() const {
  return _internal_victims_size();
}
inline void BuffData::clear_victims() {
  _impl_.victims_.Clear();
}
inline uint64_t BuffData::_internal_victims(int index) const {
  return _impl_.victims_.Get(index);
}
inline uint64_t BuffData::victims(int index) const {
  // @@protoc_insertion_point(field_get:Protocol.BuffData.victims)
  return _internal_victims(index);
}
inline void BuffData::set_victims(int index, uint64_t value) {
  _impl_.victims_.Set(index, value);
  // @@protoc_insertion_point(field_set:Protocol.BuffData.victims)
}
inline void BuffData::_internal_add_victims(uint64_t value) {
  _impl_.victims_.Add(value);
}
inline void BuffData::add_victims(uint64_t value) {
  _internal_add_victims(value);
  // @@protoc_insertion_point(field_add:Protocol.BuffData.victims)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
BuffData::_internal_victims() const {
  return _impl_.victims_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >&
BuffData::victims() const {
  // @@protoc_insertion_point(field_list:Protocol.BuffData.victims)
  return _internal_victims();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
BuffData::_internal_mutable_victims() {
  return &_impl_.victims_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint64_t >*
BuffData::mutable_victims() {
  // @@protoc_insertion_point(field_mutable_list:Protocol.BuffData.victims)
  return _internal_mutable_victims();
}

// -------------------------------------------------------------------

// ActorInfo

// int64 id = 1;
inline void ActorInfo::clear_id() {
  _impl_.id_ = int64_t{0};
}
inline int64_t ActorInfo::_internal_id() const {
  return _impl_.id_;
}
inline int64_t ActorInfo::id() const {
  // @@protoc_insertion_point(field_get:Protocol.ActorInfo.id)
  return _internal_id();
}
inline void ActorInfo::_internal_set_id(int64_t value) {
  
  _impl_.id_ = value;
}
inline void ActorInfo::set_id(int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Protocol.ActorInfo.id)
}

// float posX = 2;
inline void ActorInfo::clear_posx() {
  _impl_.posx_ = 0;
}
inline float ActorInfo::_internal_posx() const {
  return _impl_.posx_;
}
inline float ActorInfo::posx() const {
  // @@protoc_insertion_point(field_get:Protocol.ActorInfo.posX)
  return _internal_posx();
}
inline void ActorInfo::_internal_set_posx(float value) {
  
  _impl_.posx_ = value;
}
inline void ActorInfo::set_posx(float value) {
  _internal_set_posx(value);
  // @@protoc_insertion_point(field_set:Protocol.ActorInfo.posX)
}

// float posY = 3;
inline void ActorInfo::clear_posy() {
  _impl_.posy_ = 0;
}
inline float ActorInfo::_internal_posy() const {
  return _impl_.posy_;
}
inline float ActorInfo::posy() const {
  // @@protoc_insertion_point(field_get:Protocol.ActorInfo.posY)
  return _internal_posy();
}
inline void ActorInfo::_internal_set_posy(float value) {
  
  _impl_.posy_ = value;
}
inline void ActorInfo::set_posy(float value) {
  _internal_set_posy(value);
  // @@protoc_insertion_point(field_set:Protocol.ActorInfo.posY)
}

// -------------------------------------------------------------------

// ObjectInfo

// .Protocol.OBJECT_STATE_TYPE state = 1;
inline void ObjectInfo::clear_state() {
  _impl_.state_ = 0;
}
inline ::Protocol::OBJECT_STATE_TYPE ObjectInfo::_internal_state() const {
  return static_cast< ::Protocol::OBJECT_STATE_TYPE >(_impl_.state_);
}
inline ::Protocol::OBJECT_STATE_TYPE ObjectInfo::state() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.state)
  return _internal_state();
}
inline void ObjectInfo::_internal_set_state(::Protocol::OBJECT_STATE_TYPE value) {
  
  _impl_.state_ = value;
}
inline void ObjectInfo::set_state(::Protocol::OBJECT_STATE_TYPE value) {
  _internal_set_state(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.state)
}

// .Protocol.DIR_TYPE dir = 2;
inline void ObjectInfo::clear_dir() {
  _impl_.dir_ = 0;
}
inline ::Protocol::DIR_TYPE ObjectInfo::_internal_dir() const {
  return static_cast< ::Protocol::DIR_TYPE >(_impl_.dir_);
}
inline ::Protocol::DIR_TYPE ObjectInfo::dir() const {
  // @@protoc_insertion_point(field_get:Protocol.ObjectInfo.dir)
  return _internal_dir();
}
inline void ObjectInfo::_internal_set_dir(::Protocol::DIR_TYPE value) {
  
  _impl_.dir_ = value;
}
inline void ObjectInfo::set_dir(::Protocol::DIR_TYPE value) {
  _internal_set_dir(value);
  // @@protoc_insertion_point(field_set:Protocol.ObjectInfo.dir)
}

// -------------------------------------------------------------------

// TiredOfficeWorkerStat

// int32 hp = 1;
inline void TiredOfficeWorkerStat::clear_hp() {
  _impl_.hp_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_hp() const {
  return _impl_.hp_;
}
inline int32_t TiredOfficeWorkerStat::hp() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.hp)
  return _internal_hp();
}
inline void TiredOfficeWorkerStat::_internal_set_hp(int32_t value) {
  
  _impl_.hp_ = value;
}
inline void TiredOfficeWorkerStat::set_hp(int32_t value) {
  _internal_set_hp(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.hp)
}

// float healtemDropRate = 2;
inline void TiredOfficeWorkerStat::clear_healtemdroprate() {
  _impl_.healtemdroprate_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_healtemdroprate() const {
  return _impl_.healtemdroprate_;
}
inline float TiredOfficeWorkerStat::healtemdroprate() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.healtemDropRate)
  return _internal_healtemdroprate();
}
inline void TiredOfficeWorkerStat::_internal_set_healtemdroprate(float value) {
  
  _impl_.healtemdroprate_ = value;
}
inline void TiredOfficeWorkerStat::set_healtemdroprate(float value) {
  _internal_set_healtemdroprate(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.healtemDropRate)
}

// float speed = 3;
inline void TiredOfficeWorkerStat::clear_speed() {
  _impl_.speed_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_speed() const {
  return _impl_.speed_;
}
inline float TiredOfficeWorkerStat::speed() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.speed)
  return _internal_speed();
}
inline void TiredOfficeWorkerStat::_internal_set_speed(float value) {
  
  _impl_.speed_ = value;
}
inline void TiredOfficeWorkerStat::set_speed(float value) {
  _internal_set_speed(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.speed)
}

// float chaseSpeed = 4;
inline void TiredOfficeWorkerStat::clear_chasespeed() {
  _impl_.chasespeed_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_chasespeed() const {
  return _impl_.chasespeed_;
}
inline float TiredOfficeWorkerStat::chasespeed() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.chaseSpeed)
  return _internal_chasespeed();
}
inline void TiredOfficeWorkerStat::_internal_set_chasespeed(float value) {
  
  _impl_.chasespeed_ = value;
}
inline void TiredOfficeWorkerStat::set_chasespeed(float value) {
  _internal_set_chasespeed(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.chaseSpeed)
}

// int32 playerDetectionX = 5;
inline void TiredOfficeWorkerStat::clear_playerdetectionx() {
  _impl_.playerdetectionx_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_playerdetectionx() const {
  return _impl_.playerdetectionx_;
}
inline int32_t TiredOfficeWorkerStat::playerdetectionx() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.playerDetectionX)
  return _internal_playerdetectionx();
}
inline void TiredOfficeWorkerStat::_internal_set_playerdetectionx(int32_t value) {
  
  _impl_.playerdetectionx_ = value;
}
inline void TiredOfficeWorkerStat::set_playerdetectionx(int32_t value) {
  _internal_set_playerdetectionx(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.playerDetectionX)
}

// int32 playerDetectionY = 6;
inline void TiredOfficeWorkerStat::clear_playerdetectiony() {
  _impl_.playerdetectiony_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_playerdetectiony() const {
  return _impl_.playerdetectiony_;
}
inline int32_t TiredOfficeWorkerStat::playerdetectiony() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.playerDetectionY)
  return _internal_playerdetectiony();
}
inline void TiredOfficeWorkerStat::_internal_set_playerdetectiony(int32_t value) {
  
  _impl_.playerdetectiony_ = value;
}
inline void TiredOfficeWorkerStat::set_playerdetectiony(int32_t value) {
  _internal_set_playerdetectiony(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.playerDetectionY)
}

// int32 knockBackDistance = 7;
inline void TiredOfficeWorkerStat::clear_knockbackdistance() {
  _impl_.knockbackdistance_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_knockbackdistance() const {
  return _impl_.knockbackdistance_;
}
inline int32_t TiredOfficeWorkerStat::knockbackdistance() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.knockBackDistance)
  return _internal_knockbackdistance();
}
inline void TiredOfficeWorkerStat::_internal_set_knockbackdistance(int32_t value) {
  
  _impl_.knockbackdistance_ = value;
}
inline void TiredOfficeWorkerStat::set_knockbackdistance(int32_t value) {
  _internal_set_knockbackdistance(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.knockBackDistance)
}

// int32 attackRangeX = 8;
inline void TiredOfficeWorkerStat::clear_attackrangex() {
  _impl_.attackrangex_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_attackrangex() const {
  return _impl_.attackrangex_;
}
inline int32_t TiredOfficeWorkerStat::attackrangex() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.attackRangeX)
  return _internal_attackrangex();
}
inline void TiredOfficeWorkerStat::_internal_set_attackrangex(int32_t value) {
  
  _impl_.attackrangex_ = value;
}
inline void TiredOfficeWorkerStat::set_attackrangex(int32_t value) {
  _internal_set_attackrangex(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.attackRangeX)
}

// int32 attackRangeY = 9;
inline void TiredOfficeWorkerStat::clear_attackrangey() {
  _impl_.attackrangey_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_attackrangey() const {
  return _impl_.attackrangey_;
}
inline int32_t TiredOfficeWorkerStat::attackrangey() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.attackRangeY)
  return _internal_attackrangey();
}
inline void TiredOfficeWorkerStat::_internal_set_attackrangey(int32_t value) {
  
  _impl_.attackrangey_ = value;
}
inline void TiredOfficeWorkerStat::set_attackrangey(int32_t value) {
  _internal_set_attackrangey(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.attackRangeY)
}

// int32 attack = 10;
inline void TiredOfficeWorkerStat::clear_attack() {
  _impl_.attack_ = 0;
}
inline int32_t TiredOfficeWorkerStat::_internal_attack() const {
  return _impl_.attack_;
}
inline int32_t TiredOfficeWorkerStat::attack() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.attack)
  return _internal_attack();
}
inline void TiredOfficeWorkerStat::_internal_set_attack(int32_t value) {
  
  _impl_.attack_ = value;
}
inline void TiredOfficeWorkerStat::set_attack(int32_t value) {
  _internal_set_attack(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.attack)
}

// float idleTime = 11;
inline void TiredOfficeWorkerStat::clear_idletime() {
  _impl_.idletime_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_idletime() const {
  return _impl_.idletime_;
}
inline float TiredOfficeWorkerStat::idletime() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.idleTime)
  return _internal_idletime();
}
inline void TiredOfficeWorkerStat::_internal_set_idletime(float value) {
  
  _impl_.idletime_ = value;
}
inline void TiredOfficeWorkerStat::set_idletime(float value) {
  _internal_set_idletime(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.idleTime)
}

// float movingDistance = 12;
inline void TiredOfficeWorkerStat::clear_movingdistance() {
  _impl_.movingdistance_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_movingdistance() const {
  return _impl_.movingdistance_;
}
inline float TiredOfficeWorkerStat::movingdistance() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.movingDistance)
  return _internal_movingdistance();
}
inline void TiredOfficeWorkerStat::_internal_set_movingdistance(float value) {
  
  _impl_.movingdistance_ = value;
}
inline void TiredOfficeWorkerStat::set_movingdistance(float value) {
  _internal_set_movingdistance(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.movingDistance)
}

// float movementLimitX = 13;
inline void TiredOfficeWorkerStat::clear_movementlimitx() {
  _impl_.movementlimitx_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_movementlimitx() const {
  return _impl_.movementlimitx_;
}
inline float TiredOfficeWorkerStat::movementlimitx() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.movementLimitX)
  return _internal_movementlimitx();
}
inline void TiredOfficeWorkerStat::_internal_set_movementlimitx(float value) {
  
  _impl_.movementlimitx_ = value;
}
inline void TiredOfficeWorkerStat::set_movementlimitx(float value) {
  _internal_set_movementlimitx(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.movementLimitX)
}

// float movementLimitY = 14;
inline void TiredOfficeWorkerStat::clear_movementlimity() {
  _impl_.movementlimity_ = 0;
}
inline float TiredOfficeWorkerStat::_internal_movementlimity() const {
  return _impl_.movementlimity_;
}
inline float TiredOfficeWorkerStat::movementlimity() const {
  // @@protoc_insertion_point(field_get:Protocol.TiredOfficeWorkerStat.movementLimitY)
  return _internal_movementlimity();
}
inline void TiredOfficeWorkerStat::_internal_set_movementlimity(float value) {
  
  _impl_.movementlimity_ = value;
}
inline void TiredOfficeWorkerStat::set_movementlimity(float value) {
  _internal_set_movementlimity(value);
  // @@protoc_insertion_point(field_set:Protocol.TiredOfficeWorkerStat.movementLimitY)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace Protocol

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_Struct_2eproto
